### ISSUE TITLE
Adding 'cartopy' to requirements

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#183]
Chapter 7  Geographic data I/O isn't rendered, probably because I've added `cartopy` which wasn't in the requirements, not sure how to fix this, thanks!

**Comment by Robinlovelace** [comment]
Will have a look..

**Comment by michaeldorman** [comment]
Thanks @Robinlovelace

**Comment by Robinlovelace** [comment]
It seems like Cartopy is now installed in our Docker container, that was fast: https://github.com/geocompx/docker/actions/runs/5832735777/job/15818734044

**Comment by Robinlovelace** [comment]
Did that fix it @michaeldorman ?

**Comment by michaeldorman** [comment]
Yes! :-) Thank you very much @Robinlovelace

**Comment by michaeldorman** [comment]
I tried adding `osmnx` using the same method (adding into the `environment.yml` list), and now once again "Chapter 7 Geographic data I/O" isn't rendered

**Comment by Robinlovelace** [comment]
To solve this we need to

- Add it to requirements.txt, used by https://github.com/geocompx/docker/blob/master/python/Dockerfile
- Rebuild the Docker image

**Comment by Robinlovelace** [comment]
Let's see if that fixes it, in around 10 minutes. Hope so!

**Comment by Robinlovelace** [comment]
Full details from Docker build, I'm impressed at how quick packages install on the vanilla Python Docker image: https://github.com/geocompx/docker/actions/runs/5842426229/job/15843536464#step:8:2006

**Comment by Robinlovelace** [comment]
Does that fix it @michaeldorman ?

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by Robinlovelace** [comment]
![image](https://github.com/geocompx/geocompy/assets/1825120/caff6e17-3687-49d1-b0a3-60a4af1ddd47)

**Comment by michaeldorman** [comment]
> To solve this we need to
> 
>     * Add it to requirements.txt, used by https://github.com/geocompx/docker/blob/master/python/Dockerfile
> 
>     * Rebuild the Docker image

Got it! Thanks @Robinlovelace 
(How do you rebuild the Docker image?)

**Comment by michaeldorman** [comment]
> Does that fix it @michaeldorman ?

Yes, the chapter is rendered now, thanks!

**Comment by Robinlovelace** [comment]
> (How do you rebuild the Docker image?)

Edit any file in here and commit to the main branch (`master`) and it will trigger the Docker image rebuild actions.

**Comment by michaeldorman** [comment]
I think there is a similar issue now with the `contextily` package, "Chapter 8 Making maps with Python" isn't rendered. The above steps didn't seem to help, will be happy to hear if you have an idea how to solve this, thanks

**Comment by Robinlovelace** [comment]
This is looking good to me: https://py.geocompx.org/09-mapping

Fixed right @michaeldorman ?

**Comment by michaeldorman** [comment]
> This is looking good to me: https://py.geocompx.org/09-mapping
> 
> Fixed right @michaeldorman ?

Yes! Thanks @Robinlovelace

**Comment by michaeldorman** [comment]
I've added the `richdem` package to `environment.yml`, then tried to change one of the file to trigger re-building of the Docker image, but the chapter is still not rendered (<https://py.geocompx.org/03-spatial-operations.html>). I guess I'm missing something about Docker, will appreciate any help @Robinlovelace , thanks

**Comment by Robinlovelace** [comment]
Sure will take a look..

**Comment by Robinlovelace** [comment]
Hey @michaeldorman I took a look at the Docker repo but couldn't see any changes. Do you have push access? I just made a change, hopefully the new image will have the `richdem` package in there and work :crossed_fingers: 

https://github.com/geocompx/docker

**Comment by michaeldorman** [comment]
Thanks @Robinlovelace , I checked and it's not working yet - when I uncomment the `richdem` code in Chapter 3, the chapter isn't rendered anymore
![Screenshot from 2023-09-27 00-56-57](https://github.com/geocompx/geocompy/assets/9386655/cb4c769d-a0e0-4064-97fc-75225f6e1a5f)

**Comment by Robinlovelace** [comment]
I see.. I now realise that the Docker images use `pip` as the package manager and use the requirements.txt: 

https://github.com/geocompx/docker/blob/master/python/Dockerfile#L11

We need a way to auto update that based on `environment.yml`.


Currently running

```bash
micromamba update -f environment.yml 
```

**Comment by Robinlovelace** [comment]
Apologies, I now see `richdem` is in https://github.com/geocompx/geocompy/blob/main/requirements.txt

**Comment by Robinlovelace** [comment]
Testing locally with

```
docker pull ghcr.io/geocompx/docker:python
```

**Comment by Robinlovelace** [comment]
Underlying problem: installation of `richdem` failed: https://github.com/geocompx/docker/actions/runs/6317840710/job/17155518300#step:8:2552

**Comment by Robinlovelace** [comment]
This seems to be a known issue with the package: https://github.com/r-barnes/richdem/issues/65

**Comment by Robinlovelace** [comment]
Chapter is now back up: https://py.geocompx.org/03-spatial-operations

![image](https://github.com/geocompx/geocompy/assets/1825120/d7291863-1ba4-4bdd-b227-d675e46d0297)

In the long term this is not an ideal solution. If https://github.com/r-barnes/richdem/issues/65 cannot be fixed it may be worth looking at alternatives or mentioning issues with installing the package with pip + Python 3.11.

**Comment by michaeldorman** [comment]
Thanks for the thorough check @Robinlovelace ! I agree that this is not an ideal situation, if necessary perhaps we can use `gdaldem` from the command line for this example, or look for other alternatives

**Comment by Robinlovelace** [comment]
https://gdal.org/programs/gdaldem.html looks like a great solution if it can work, surely there's a Python wrapper?

**Comment by michaeldorman** [comment]
> https://gdal.org/programs/gdaldem.html looks like a great solution if it can work, surely there's a Python wrapper?

I think so, will add an issue so that we remember to check it out

**Comment by michaeldorman** [comment]
I think this was already completed by @Robinlovelace , so closing

**Comment by Robinlovelace** [comment]
Thanks for closing this Michael.
